BOX_IMAGE  = "debian/bullseye64"
ETCD_COUNT = 3
MINIONS = 3
MASTER_COUNT = 2

Vagrant.configure("2") do |config|
  # Master / Controllers 
  (1..MASTER_COUNT).each do |i|
    config.vm.define "master-#{i}" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master-#{i}"
    subconfig.vm.network :private_network, ip: "10.0.0.#{20+i}"
    end
  end
  # ETCD Nodtes
  (1..ETCD_COUNT).each do |i|
    config.vm.define "etcd-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "etcd-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{10+i}"
    end
  end
  # Minions
  (1..MINIONS).each do |i|
    config.vm.define "worker-#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "worker-#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{30+i}"
    end
  end

   # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y avahi-daemon libnss-mdns
  SHELL
 end
